### PR TITLE
Test unsupported features

### PR DESCRIPTION
**Pull request by jayvdb**
Sits on top of https://github.com/adsharma/py2many/pull/186 and https://github.com/adsharma/py2many/pull/185

TODO:
- ~~Remove extra ';' added to nim~~

### CODE REVIEW

**Comment by jayvdb** [comment]
The output of the unsupported skips is often quite ugly.  This can be fixed quite easily by detecting and raising `NotImplementedError`, or by fixing them of course.

**Comment by adsharma** [comment]
Do you know if the regression in CI runtimes is caused by something in this diff stack or something happening on github backends? 25 mins for mac/windows seems high.

**Comment by jayvdb** [comment]
11 mins for invocation of `tox` on Ubuntu.

**Comment by jayvdb** [comment]
Also number of tests increases from 207 -> 389.  Coverage increases 2%, with non-branch missings going from 930 to 820; `py2many/declaration_extractor.py` coverage goes from 66% to 82%

**Comment by adsharma** [comment]
Ah I see. Gives us an incentive to fix all those cases so the tests will be faster :)

**Pull request merged**
