### PR TITLE
main: simplify the method signature

### PR DESCRIPTION
**Pull request by adsharma**

### CODE REVIEW

**Comment by jayvdb** [comment]
Please no.  My design is not broken, as I explained in https://github.com/adsharma/py2many/pull/256#discussion_r637569301 .  The C entry point is the common interface.  We will need to use `proc cmain` and `#[start]` and others when we implement more features, mark my words.  We will be implementing languages other than C++ which do require `argc` in their main signature.

**Comment by jayvdb** [comment]
A better way to achieve this is for each language to declare whether they need `argc` or `argv`, so the generic rewriter can use that info to generate the appropriate generic signature.  I could put up a PR to demo that if you're not 100% committed to your PR.

**Comment by adsharma** [comment]
> A better way to achieve this is for each language to declare whether they need `argc` or `argv`, so the generic rewriter can use that info to generate the appropriate generic signature. I could put up a PR to demo that if you're not 100% committed to your PR.

Yeah - this seems preferable. The implementation could be one PythonMainRewriter per language.

I'll put this on hold until I understand your idea.

**Comment by jayvdb** [comment]
This can be closed now ?

**Comment by jayvdb** [comment]
ping @adsharma

**Comment by adsharma** [comment]
Covered by  other PRs

**Pull request closed without merging**
