### PR TITLE
Simplify assign one

### PR DESCRIPTION
**Pull request by adsharma**
Related to https://github.com/adsharma/py2many/issues/410

### CODE REVIEW

**Review by jayvdb — COMMENTED** [review]
https://github.com/adsharma/py2many/commit/6378f1598b3f8cc3822f95464ba18ee04ed2f9d4 references #410, but it seems to be unrelated, as it is seemingly/just re-blaming code with any improvement to the output.

The issue is that coverage.py should be
```diff
-a9: List[str] = ["a", "b", "c", "d"]
+a9 = ["a", "b", "c", "d"]
```

And then the problem is fixed if `coverage.rs` does not include this:
```diff
-    let a9: Vec<&str> = vec!["a", "b", "c", "d"];
+    let a9: &Vec<&str> = &vec!["a", "b", "c", "d"];
```

**Comment by adsharma** [comment]
It's deleting the special code paths for lists, since the normal code paths is general enough.
This diff stack trims around ~40 lines.

Re: the problem python, julia, kotlin have

They add a type annotation only in `visit_AnnAssign`, even if there is an inferred one.
The fix should be to change `visit_AssignOne` to add the annotation just like pyrs does.

That leaves a few minor issues:

* final vs no final on dart (I think final is more correct)
* Reference vs no reference on Rust

**Comment by adsharma** [comment]
Correction: only julia and kotlin have this problem.

Python is ok and handled by InferredAnnAssignRewriter

**Comment by adsharma** [comment]
One option is to add this rewriter to other languages that need it:

https://paste.ubuntu.com/p/W3Sm6k5cZQ/

But right now it opens up other problems that I'm not sure we can solve before v0.3

**Review by jayvdb — APPROVED** [review]

**Pull request merged**
