### PR TITLE
pygo: Provide a default return if not inferred 

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/adsharma/py2many/issues/402

### CODE REVIEW

**Comment by jayvdb** [comment]
This still fails `infer_ops`.  I'll get to that soon.  But I dont mind if this doesnt make it into v0.3.0 ; it is only replacing one problem with a different more predicable problem.

**Comment by jayvdb** [comment]
After this change, the only gofmt error for the sample on https://github.com/adsharma/py2many/issues/402 is
```
./cls.go:11:9: undefined: x
```

And now most of the go self transpilation is successful except for gofmt errors.

**Comment by adsharma** [comment]
Looks good. Perhaps rebase on top of #396 ?

**Comment by adsharma** [comment]
Closed via 0a043bd

**Pull request closed without merging**
