### PR TITLE
tests: add a test for directory mode

### PR DESCRIPTION
**Pull request by adsharma**
Related to: https://github.com/adsharma/py2many/issues/391

### CODE REVIEW

**Comment by adsharma** [comment]
Not sure how tests/expected/*.py are ignored in pyflakes. I should probably use the same mechanism.

**Comment by jayvdb** [comment]
`rm tests/cases/*.py tests/expected/*.py` in https://github.com/adsharma/py2many/blob/main/.github/workflows/main.yml#L121-L122

**Comment by adsharma** [comment]
go, julia, kotlin, nim and rust fail the newly added test, only on windows.
Failure mode: no files in the target dir.

I first thought if it's an issue with handling paths. In that case - cpp and dart should fail too. But they pass.

**Comment by jayvdb** [comment]
IMO, raise `SkipTest` on Windows for this test on any that dont pass.

We already have bad Windows support, and this is just another issue to add to it.

Lets get this in and fix release blockers.

**Comment by jayvdb** [comment]
for reference, https://github.com/adsharma/py2many/issues/339 is the issue about Julia and Kotlin failing on Windows.

btw, https://github.com/adsharma/py2many/pull/390 is ready

**Comment by adsharma** [comment]
Noting the debug information here and going with your suggestion of SkipTest:

```
>           assert output.diff_files == []
E           AssertionError: assert ['bar.go', 'baz.go', 'foo.go'] == []
E             Left contains 3 more items, first extra item: 'bar.go'
E             Full diff:
E             - []
E             + ['bar.go', 'baz.go', 'foo.go']

D:\a\py2many\py2many\tests\test_cli.py:447: AssertionError
---------------------------- Captured stdout call -----------------------------
Transpiling whole directory to D:\a\py2many\py2many\tests\dir_cases\test1-go-generated:
writing to: D:\a\py2many\py2many\tests\dir_cases\test1-go-generated\bar.go 47 bytes
writing to: D:\a\py2many\py2many\tests\dir_cases\test1-go-generated\bar.go done
writing to: D:\a\py2many\py2many\tests\dir_cases\test1-go-generated\baz.go 54 bytes
writing to: D:\a\py2many\py2many\tests\dir_cases\test1-go-generated\baz.go done
writing to: D:\a\py2many\py2many\tests\dir_cases\test1-go-generated\foo.go 168 bytes
writing to: D:\a\py2many\py2many\tests\dir_cases\test1-go-generated\foo.go done

Finished!
Successful: 3
Failed to convert: 0
```

**Comment by adsharma** [comment]
It certainly looks like a race condition, where py2many/cli.py:_format_one() is still running the formatter in the background, even after `run()` has returned. Documentation says it returns only after the process has completed.

Working around by ignoring exceptions inside `_recursive_rmdir`

**Pull request merged**
