### PR TITLE
tests: Add __main__ to enum tests

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/adsharma/py2many/issues/25

### CODE REVIEW

**Review by adsharma — APPROVED** [review]
This one looks good to go after rebase.

**Comment by jayvdb** [comment]
Yay.  It passed.  So there is something very odd about the previous CI failure of macOS - something to remember if it re-occurs.

**Comment by jayvdb** [comment]
for the record, the macOS CI failure was

https://github.com/adsharma/py2many/runs/2375004681?check_suite_focus=true

as the logs will be deleted as stale after a while, here is the relevant section
```
_______________ CodeGeneratorTests.test_cli__<'infer', 'kotlin'> _______________

self = <test_cli.CodeGeneratorTests testMethod=test_cli__<'infer', 'kotlin'>>
case = 'infer', lang = 'kotlin'

    @foreach(SETTINGS.keys())
    @foreach(TEST_CASES)
    def test_cli(self, case, lang):
        settings = self.SETTINGS[lang]
        ext = settings.ext
        if (
            not UPDATE_EXPECTED
            and not KEEP_GENERATED
            and not os.path.exists(f"expected/{case}{ext}")
        ):
            raise unittest.SkipTest(f"expected/{case}{ext} not found")
        if settings.formatter:
            if not spawn.find_executable(settings.formatter[0]):
                raise unittest.SkipTest(f"{settings.formatter[0]} not available")
    
        if ext == ".kt":
            class_name = str(case.title()) + "Kt"
            exe = TESTS_DIR / (class_name + ".class")
        if ext == ".dart" or (ext == ".nim" and sys.platform == "win32"):
            exe = TESTS_DIR / "cases" / f"{case}.exe"
        else:
            exe = TESTS_DIR / "cases" / f"{case}"
        exe.unlink(missing_ok=True)
    
        case_filename = TESTS_DIR / "cases" / f"{case}.py"
        case_output = TESTS_DIR / "cases" / f"{case}{ext}"
        is_script = has_main(case_filename)
        sys.argv = ["test", f"--{lang}=1", str(case_filename)]
    
        if case in COMPARABLE:
            expected_output = run(
                [sys.executable, str(case_filename)], capture_output=True, check=True
            ).stdout
            self.assertTrue(expected_output)
            expected_output = expected_output.splitlines()
        else:
            expected_output = None
    
        try:
            main()
            with open(f"cases/{case}{ext}") as actual:
                generated = actual.read()
                if os.path.exists(f"expected/{case}{ext}") and not UPDATE_EXPECTED:
                    with open(f"expected/{case}{ext}") as f2:
>                       self.assertEqual(f2.read(), generated)
E                       AssertionError: 'fun foo() {\n    val a = 10\n    val b = [72 chars]n}\n' != '\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\[383 chars]\x00'
E                       + - fun foo() {
E                       -     val a = 10
E                       -     val b = a
E                       -     assert(b == 10)
E                       -     println("$b")
E                       - }
E                       - 
E                       - fun main() {
E                       -     foo()
E                       - }

/Users/runner/work/py2many/py2many/tests/test_cli.py:129: AssertionError
----------------------------- Captured stdout call -----------------------------
Writing to: /Users/runner/work/py2many/py2many/tests/cases
/Users/runner/work/py2many/py2many/tests/cases/infer.py...cases/infer.kt
----------------------------- Captured stderr call -----------------------------
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.jetbrains.kotlin.com.intellij.util.ReflectionUtil (file:/usr/local/Cellar/ktlint/0.41.0/libexec/ktlint) to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
WARNING: Please consider reporting this to the maintainers of org.jetbrains.kotlin.com.intellij.util.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by adsharma** [comment]
Merged as 510f310

**Comment by jayvdb** [comment]
Grr.  You could have fast-forward and added 2dec5d4 on top :/

**Comment by adsharma** [comment]
I could've, yes. I got to your pull requests after I landed that trivial
safety diff (it was time sensitive because I posted to a hackernews thread
and wanted anyone who tried it out to not have an error). Did it make any
difference?

Expecting that your commit hashes remain exactly the same in a project
where more than one person is checking in code seems ... rather unique.

I'd focus more on code than the commit hashes.

**Pull request closed without merging**
