### PR TITLE
binit: make it executable

### PR DESCRIPTION
**Pull request by adsharma**

### CODE REVIEW

**Comment by adsharma** [comment]
Fixes dart, kt as well.

**Comment by jayvdb** [comment]
Lots of great fixes here, but go and rs still dont compile in CI
SKIPPED [1] tests/test_cli.py:76: binit.go doesnt compile
SKIPPED [1] tests/test_cli.py:76: binit.rs doesnt compile

For any that you have fixed, please remove the entry in `tests_cli.py`:
```py
    "binit.go",  # https://github.com/adsharma/py2many/issues/23
    "binit.nim",  # https://github.com/adsharma/py2many/issues/19
    "binit.rs",  # https://github.com/adsharma/py2many/issues/19
```

**Comment by jayvdb** [comment]
Or change binit.py to use simpler syntax so this PR can properly resolve https://github.com/adsharma/py2many/issues/23 and https://github.com/adsharma/py2many/issues/19 , and we can have a separate test case / issues for the bits not yet fully solved.

**Comment by adsharma** [comment]
> but go and rs still dont compile in CI

Correct. Go is close, but not there yet. Rust requires handling type inference/casting.
Dart, Kt weren't in the list of skipped tests (they failed to compile earlier, but now compile and run).

Re: changing syntax

Let me see if I can implement rust type casts. Fixing the underlying issue has the benefit that more real world programs have a chance of working correctly.

**Pull request merged**
