### PR TITLE
tests: Move builds into dedicated directory

### PR DESCRIPTION
**Pull request by jayvdb**
This problem was raised in https://github.com/adsharma/py2many/issues/311#issuecomment-853484870

### CODE REVIEW

**Comment by jayvdb** [comment]
I think I need to move the generated output into `tests/build` for dart to pick up the generated `pubspec.yaml`.

**Comment by adsharma** [comment]
tests/__init__.py seems to be missing. Could you add it in one of your other PRs?

**Comment by jayvdb** [comment]
`tests/__init__.py` is only needed in py2

**Comment by adsharma** [comment]
```
pytest-3 -k rust -v
```

fails without it.

**Pull request merged**
